### ISSUE TITLE
Convert Toolbox from XML to JSON

### ISSUE THREAD

**Issue by Malix-Labs** [scratch-for-discord/scratch-for-discord#113]
## Reason

https://developers.google.com/blockly/guides/configure/web/serialization:
  > Blockly provides two formats for this data: JSON and XML. We recommend using the JSON system for new projects, and encourage older projects using XML to upgrade. The XML system is the legacy save format. It will not be removed, but it will not receive new features.

## Subject

- **File** : <https://github.com/scratch-for-discord/Web-Application_Frontend/blob/release/2/master/src/toolbox.ts>

## Links

- **[npm package](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/113#issuecomment-1318389663)**

**Comment by Malix-Labs** [comment]
- External Thought from @ItsLimeNade:
> It should be possible to be done with a npm package
<https://www.npmjs.com/search?q=xml%20to%20json>
maybe this one: <https://www.npmjs.com/package/xml2js>

**Comment by retrouser955** [comment]
I do not recommand this. XML looks much cleaner than JSON in this case.

**Comment by RedMan13** [comment]
yeah .xml toolbox looks way better then .json (and makes more sense) so is would only do json serialization change.
and that cant rlly be done for the current master v2 branch

**Comment by Malix-Labs** [comment]
- [Comment Reply](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/113#issuecomment-1318405562) from @retrouser955:
  > I do not recommand this. XML looks much cleaner than JSON in this case.
- [Comment Reply](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/113#issuecomment-1318409529) from @RedMan13:
  > yeah .xml toolbox looks way better then .json (and makes more sense) [[…]](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/113#issuecomment-1318409529)

I believe [blockly has deprecated XML use](https://developers.google.com/blockly/guides/configure/web/serialization) anyway.
What do you guys @JeremyGamer13 and @ItsLimeNade think about this?

**Comment by retrouser955** [comment]
No blockly still support XML I think. Can you send the link of where you heard this from?

**Comment by Malix-Labs** [comment]
- [Comment Reply](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/113#issuecomment-1318413316) from @retrouser955:
  > No blockly still support XML I think. Can you send the link of where you heard this from?

https://developers.google.com/blockly/guides/configure/web/serialization:
  > Blockly provides two formats for this data: JSON and XML. We recommend using the JSON system for new projects, and encourage older projects using XML to upgrade. The XML system is the legacy save format. It will not be removed, but it will not receive new features.

**Comment by RedMan13** [comment]
> * [Comment Reply](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/113#issuecomment-1318405562) from @retrouser955:
>   > I do not recommand this. XML looks much cleaner than JSON in this case.
> * [Comment Reply](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/113#issuecomment-1318409529) from @RedMan13:
>   > yeah .xml toolbox looks way better then .json (and makes more sense) [[…]](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/113#issuecomment-1318409529)
> 
> I believe [blockly has deprecated XML use](https://developers.google.com/blockly/guides/configure/web/serialization) anyway. What do you guys @JeremyGamer13 and @ItsLimeNade think about this?

they have only deprecated xml [**serialization**](https://developers.google.com/blockly/guides/configure/web/serialization) not xml toolbox, the only downside to using xml toolbox is you have to use xml serialization for [preset blocks](https://developers.google.com/blockly/guides/configure/web/toolbox#preset_blocks) (this may not actually be true tho)

**Comment by Malix-Labs** [comment]
- [Comment Reply](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/113#issuecomment-1318427908) from @RedMan13:
  > [[…]](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/113#issuecomment-1318427908) the only downside to using xml toolbox is you have to use xml serialization for [preset blocks](https://developers.google.com/blockly/guides/configure/web/toolbox#preset_blocks) [[…]](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/113#issuecomment-1318427908)

...and also
  > it will not receive new features.

**Comment by Malix-Labs** [comment]
@retrouser955 @RedMan13 I do confirm we will change everything from XML to JSON due to preventing the deprecation of blockly XML features.

**Comment by Malix-Labs** [comment]
@RedMan13 do you testify that nothing in s4d uses XML anymore, including toolbox, workspaces, and the .s4d file with serialization?
