### ISSUE TITLE
Move the React Web-app Repo to a Branch in this Repo

### ISSUE THREAD

**Issue by Malix-Labs** [scratch-for-discord/scratch-for-discord#18]
From [github.com/scratch-for-discord/scratch-for-discord-react](https://github.com/scratch-for-discord/scratch-for-discord-react) to a new branch named "`v3`" in [github.com/scratch-for-discord/Web-Application](https://github.com/scratch-for-discord/Web-Application)

**Comment by retrouser955** [comment]
done [here](https://github.com/scratch-for-discord/Web-Application_Frontend/tree/v3-react)
