### ISSUE TITLE
Get category/channel with [ID] equal to (input) on server (server)

### ISSUE THREAD

**Issue by RedMan13** [scratch-for-discord/scratch-for-discord#28]
## Subject

**Block Option**

"`ID`" option in block

> `Get category/channel with [option] equal to (input) on server (server)`

![`Get category/channel with [option] equal to (input) on server (server)`](https://cdn.discordapp.com/attachments/1015067128715554906/1025658127191900232/unknown.png)

## Examples

- ![(s4dmessage.guild).channels.cache.get((category) => category.id === '1015067128715554906').send('test')](https://cdn.discordapp.com/attachments/1015067128715554906/1025658863061581864/unknown.png)
- ![(s4dmessage.guild).channels.cache.get((category) => category.id === '1015067128715554906').id](https://cdn.discordapp.com/attachments/1015067128715554906/1025658862679883828/unknown.png)

## Location

[src/blocks/frostzzone/useful/category/categoryget.js](https://github.com/scratch-for-discord/Web-Application_Frontend/blob/e3b775731f36bf04f6270a2cf1eba05271fcbad2/src/blocks/frostzzone/useful/category/categoryget.js)

## Finder

@RedMan13

**Comment by RedMan13** [comment]
just now occurred to me that the hyper link in category/channel is also rlly bad and also kinda implys it will link to the block file
it doesn. it links to an image of the block the block file is at src/blocks/frostzzone/useful/category/categoryget.js

**Comment by RedMan13** [comment]
link https://github.com/frostzzone/scratch-for-discord/blob/test/src/blocks/frostzzone/useful/category/categoryget.js and as mentioned already the issue is with the id option only

**Comment by Malix-Labs** [comment]
- [x] Update this issue description (@Malix-Off)

**Comment by Malix-Labs** [comment]
@RedMan13 feel free to assign yourself on this issue
