### ISSUE TITLE
Web Code Editor Integration 

### ISSUE THREAD

**Issue by Malix-Labs** [scratch-for-discord/scratch-for-discord#52]
## Explaination

Replacing the outputed JavaScript code pop-up with a web code editor integration.

## Tasks

- [ ] Finding the best web code editor integration
- [ ] Integrate it

## Links

- ~~**[vscode.dev](https://vscode.dev/)**~~ (not integrable)

**Comment by nekoify** [comment]
what

**Comment by RedMan13** [comment]
> @CatSoup1 
> what

make a vscode extension for s4d (put s4d in vscode)

**Comment by CatSoup1** [comment]
uh

**Comment by nekoify** [comment]
how would i put s4d in say vscode

**Comment by Malix-Labs** [comment]
- [Comment Reply](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/52#issuecomment-1370621759) from @nekoify:
  > how would i put s4d in vscode

We don't want to put s4d into vscode, but to put a web code editor integration into s4d.
By replacing the output JavaScript code pop-up with a web code editor integration.
I think it is possible, and require minor tweaking about how blocks export/output code.
Also, a good web code editor integration would probably already includes source-control, and if it's true, this issue will also complete #32 by itself

**Comment by Malix-Labs** [comment]
As [vscode.dev](https://vscode.dev/) is not integrable, this issue has been changed to a more general "web code editor integration" subject

**Comment by Malix-Labs** [comment]
Do someone know what would be the best web code editor integration?
Something as good as vsc web (with multiple files and a complete source-control), but integrable

**Comment by Malix-Labs** [comment]
I can't find any good web code editor integration with multi-file and source-control

**Comment by RedMan13** [comment]
source control is easy and multi files will have to be made by hand anyways so why not jsut use the [vue monaco editor](https://www.npmjs.com/package/monaco-editor-vue)

**Comment by Malix-Labs** [comment]
I think codemirror is better

**Comment by Malix-Labs** [comment]
https://discuss.codemirror.net/t/git-source-control/5516

**Comment by RedMan13** [comment]
theres little difference that i can see

**Comment by Malix-Labs** [comment]
Maybe we should just use [Prism.js](https://prismjs.com/) and do the rest ourselves

**Comment by Malix-Labs** [comment]
There is not any web code editor integration that features multi-files or source-control

**Comment by RedMan13** [comment]
make sense since like they expect you to do that

**Comment by Malix-Labs** [comment]
- [Comment Reply](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/52#issuecomment-1370758285) from @RedMan13:
  > [[…]](https://github.com/scratch-for-discord/Web-Application_Frontend/issues/52#issuecomment-1370758285) they expect you to do that

Yes, but no-code web-apps are a thing now, and the best ones facilitate coding (instead of substituing to it), so also include a code editor.

**Comment by Malix-Off** [comment]
@RedMan13 read again

**Comment by RedMan13** [comment]
it is imposible for a web app to have no code

**Comment by RedMan13** [comment]
its imposible for any app to have no code

**Comment by Malix-Labs** [comment]
> its imposible for any app to have no code

I'm talking about "no-code web-applications", such as Scratch, Zapier and S4D

**Comment by RedMan13** [comment]
ah
those apps to, just do it themselves

**Comment by RedMan13** [comment]
> ah those apps to, just do it themselves

*to be clear i only know this from s4d and scratch, i do not know anything about zapier and others*

**Comment by Malix-Labs** [comment]
> those apps to, just do it themselves

What does it mean?

**Comment by RedMan13** [comment]
> > those apps to, just do it themselves
> 
> What does it mean?

they dont use pre made things for like any of it, they only use modules and stuff for the things each thing is doing

like they only use external functions to simplify the main functions that are doing the things like rendering the categorys and runing the code, they dont use a pre made module to run the code

**Comment by Malix-Labs** [comment]
> they dont use pre made things for like any of it, they only use modules and stuff for the things each thing is doing
> 
> like they only use external functions to simplify the main functions that are doing the things like rendering the categorys and runing the code, they dont use a pre made module to run the code

I was mainly talking about the code editor modules: no-code web-apps usually do not even integrate code editors.
It would be nice if we could integrate a code editor into s4d, but the thing is that there only are rudimentary ones (mainly because our use of it would be quite niche, even for a no-code web-app)

**Comment by RedMan13** [comment]
ah yeah because of the lack of demand no such things your looking for will exist

they will have to be made by hand
