### ISSUE TITLE
Deleted Channel

### ISSUE THREAD

**Issue by RedMan13** [scratch-for-discord/scratch-for-discord#65]
the block `deleted channel`  and `created channel` returns channel.channel which returns undefined
this doesnt need fixed immediately but it does need fixed at some point
the current solution is to use id of deleted/created channel and geting channel from that

**Comment by Malix-Labs** [comment]
@RedMan13 can you fix that yourself? if yes, please assign yourself to it.

**Comment by RedMan13** [comment]
uh not rn bc im working on other stuff but yeah
